Fixing tracing macro errors with the latest VC++.
Got a new error emitted:
`error C4576: a parenthesized type followed by an initializer
list is a non-standard explicit type conversion syntax`

Unfortunately C99 supports paren-init and not non-paren-init and
C++ supports the opposite so this error is dumb. Oh well.