Use SmallVector instead of std::vector
We can avoid allocation to some extent and this also resolves the
compilation error on Windows:

  error: indirection requires pointer operand

Closes #79

COPYBARA_INTEGRATE_REVIEW=https://github.com/google/iree/pull/79 from antiagainst:smallvector 43aad01666d54207ad0797ea6dfc7ce9a91f39bf
PiperOrigin-RevId: 275746117